#!/usr/bin/env python3
"""
Generate the on-demand skill MANIFEST block inside claude-code/SKILLS.md.

Why this exists
---------------
Model A deploys only the skills listed in `claude-code/skills-core.txt` to
`~/.claude/skills`. Those are discovered natively by Claude Code, so their
`description` is already in context every session — indexing them again in
SKILLS.md is duplication.

Every OTHER skill stays in the repo and is invisible to the agent unless a
*context pointer* names it. That pointer is the MANIFEST: one line per
non-core skill, holding just enough to decide "this is the one" and resolve
the path. Without it, a skill on disk does not exist as far as the agent is
concerned.

The block is delimited by markers so the hand-written spine of SKILLS.md
(global rules + always-on disciplines) is never touched:

    <!-- MANIFEST:START (generated by scripts/_generate_manifest.py) -->
    ...
    <!-- MANIFEST:END -->

Usage
-----
    python3 scripts/_generate_manifest.py            # rewrite the block in place
    python3 scripts/_generate_manifest.py --stdout   # print the block, write nothing
    python3 scripts/_generate_manifest.py --check    # exit 1 if the block is stale
    python3 scripts/_generate_manifest.py --report   # coverage + duplication report

`--check` is the invariant to wire into deploy.sh: the index may not drift
from the skills that actually exist.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
SKILLS_DIR = BASE / "skills"
CORE_LIST = BASE / "claude-code" / "skills-core.txt"
SKILLS_MD = BASE / "claude-code" / "SKILLS.md"

START = "<!-- MANIFEST:START (generated by scripts/_generate_manifest.py) -->"
END = "<!-- MANIFEST:END -->"

# Replaced by deploy.sh with the absolute path of this clone's skills/ dir.
SKILLS_ROOT_TOKEN = "__OSFORGE_SKILLS_ROOT__"

# Flat .md files that are not skills at all.
NOT_A_SKILL = {"README.md", "AGENTS.md", "CLAUDE.md"}

TRIGGER_MAX = 78

sys.path.insert(0, str(BASE / "scripts"))
from _extract_index import extract_frontmatter  # noqa: E402


# ── grouping ─────────────────────────────────────────────────────────────────
#
# Deliberately NOT reusing categorize_skill() from _extract_index.py: it scans
# the whole description for keywords and first-match-wins, so `accessibility`
# ("Audit and improve…") lands in Security and `database-design` ("…index…")
# with it. A miscategorised pointer is worse than no category — the agent scans
# the wrong section and concludes the skill does not exist. These rules match
# name + path only, in order, and are boring on purpose.

GROUPS: list[tuple[str, str]] = [
    (r"^offensive-|^red-team|pentest|vulnerability|^security|^insecure-|^gdpr|^secrets?-", "🔒 Security & Offensive"),
    (r"^agency/", "🏢 Agency (role playbooks)"),
    (r"^imagegen-|^brandkit|^stitch-|taste|^design|design$|^redesign-|^high-end-|^minimalist-|^ui-|^web-design|^frontend-design|^aesthetic-|^openui-|^image-to-code", "🎨 Design & Visual"),
    (r"^tdd|test|^e2e-|^qa-|coverage|^predictive-failure", "🧪 Testing"),
    (r"^spec-|^planning/|^tlc-|^brainstorm|^epic-|^story-|^prd-|^phase-|^requirements-|^visual-planner|^plan-", "📋 Planning & Spec"),
    (r"^quality/|review|^lint-|^clean-code|^refactor|^verification-", "🔍 Review & Quality"),
    (r"^context/|^context-|^memory|^rag|^embedding|^doc-shard|^stuck-recovery", "🧠 Context & Memory"),
    (r"^git|^deploy|^aws-|^docker|^ci-|^devops|^finishing-|^observability|^monitoring", "☁️ DevOps & Git"),
    (r"^nextjs|^react|^prisma|^supabase|^better-auth|^stripe|^asaas|^bun|^tailwind|^shadcn|^node|^python|^rust|^bash|^database|^api-", "🧱 Stack & Languages"),
    (r"^claude-|^skill-|^mcp-|^agent-|^smart-|^dispatching-|^autorefine|^config-critique|^behavioral-|^llm-|^prompt", "🤖 Claude & Agents"),
    (r"^seo|^marketing|^growth|^copywriting|^humanizer|^content", "💼 Marketing & Content"),
    (r"^docs?-|^documentation|^writing|^readme|^changelog", "📝 Documentation"),
    (r"^game-|^mobile-|^expo", "🎮 Game & Mobile"),
]


def group_of(name: str, rel: str) -> str:
    hay = f"{rel} {name}".lower()
    for pattern, label in GROUPS:
        if re.search(pattern, hay):
            return label
    return "📦 General"


# ── parsing ──────────────────────────────────────────────────────────────────

def load_core() -> set[str]:
    """Relative paths under skills/ that deploy.sh ships globally."""
    if not CORE_LIST.exists():
        return set()
    out = set()
    for line in CORE_LIST.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            out.add(line)
    return out


def triggers_from(description: str, fallback: str) -> str:
    """
    Collapse a description down to its activation core.

    Preference order mirrors the OSForge activation pattern (SKILL-STANDARD §3):
    `Keywords:` is the densest form, `Use when:` the next best, and the leading
    clause is the last resort. Everything else in the description is identity,
    which the manifest deliberately drops — the agent only needs enough to
    decide whether to open the file.
    """
    if not description:
        return fallback

    text = re.sub(r"\s+", " ", description).strip()

    m = re.search(r"Keywords?:\s*(.+?)(?:\.\s*(?:Do NOT|Don't|Use when)|$)", text, re.I)
    if m:
        cand = m.group(1)
    else:
        # `Use when:` is the standard (SKILL-STANDARD §3); `Trigger on/Triggers on`
        # is the legacy phrasing still present in unmigrated skills.
        m = re.search(
            r"(?:Use when|Triggers? on|Trigger)\s*:?\s*(.+?)(?:\s*Keywords?:|\s*Do NOT|$)",
            text, re.I,
        )
        cand = m.group(1) if m else text

    cand = cand.strip().strip("`").strip()
    cand = re.sub(r"\s*[.;]\s*$", "", cand).rstrip(".").strip()

    if len(cand) > TRIGGER_MAX:
        cut = cand[:TRIGGER_MAX]
        # prefer cutting on a list separator so a trigger is never half a word
        for sep in (", ", "; ", " "):
            if sep in cut:
                cut = cut[: cut.rfind(sep)]
                break
        cand = cut.rstrip(",;: ") + "…"

    return cand or fallback


def collect_skills() -> list[dict]:
    skills = []
    for sf in sorted(SKILLS_DIR.rglob("SKILL.md")):
        rel = sf.parent.relative_to(SKILLS_DIR).as_posix()
        content = sf.read_text(encoding="utf-8", errors="replace")
        name, desc = extract_frontmatter(content)
        name = (name or sf.parent.name).strip()
        skills.append({
            "name": name,
            "rel": rel,
            "dir": sf.parent.name,
            "desc": desc,
            "triggers": triggers_from(desc, sf.parent.name.replace("-", " ")),
            "category": group_of(name, rel),
        })
    return skills


def collect_knowledge() -> list[dict]:
    """
    Flat `.md` modules under skills/<group>/ — the legacy format, no frontmatter,
    a `**Trigger:**` line instead. They are never deployed natively, so they are
    only ever reachable through the manifest.
    """
    skill_dirs = {sf.parent.name for sf in SKILLS_DIR.rglob("SKILL.md")}
    out = []
    for p in sorted(SKILLS_DIR.glob("*/*.md")):
        if p.name == "SKILL.md" or p.name in NOT_A_SKILL:
            continue
        duplicate_of = p.stem if p.stem in skill_dirs else None
        text = p.read_text(encoding="utf-8", errors="replace")
        m = re.search(r"^\*\*Trigger:?\*\*:?\s*(.+)$", text, re.M)
        trig = triggers_from(m.group(1) if m else "", p.stem.replace("-", " "))
        title = ""
        t = re.search(r"^#\s+(.+)$", text, re.M)
        if t:
            title = t.group(1).strip()
        out.append({
            "name": title or p.stem,
            "rel": p.relative_to(SKILLS_DIR).as_posix(),
            "triggers": trig,
            "duplicate_of": duplicate_of,
        })
    return out


# ── rendering ────────────────────────────────────────────────────────────────

def render(skills: list[dict], knowledge: list[dict], core: set[str]) -> str:
    non_core = [s for s in skills if s["rel"] not in core]
    # Every knowledge module is indexed, including the 30 whose filename collides
    # with a skill: their content overlaps the skill by only 6-89%, so dropping
    # them would hide material, not remove a copy. The collision is disambiguated
    # inline by a precedence rule rather than by omission — an ambiguous pointer
    # and a missing pointer fail the same way.
    live_knowledge = knowledge

    lines: list[str] = [START, ""]
    lines.append("# On-Demand Manifest")
    lines.append("")
    lines.append(
        f"The {len(non_core)} skills below are **not** deployed to `~/.claude/skills` "
        "(Model A ships only the core allowlist), so the agent cannot see them by "
        "description. This manifest is their only pointer — treat it as authoritative."
    )
    lines.append("")
    lines.append("**Resolution protocol — never conclude a capability is unavailable without running it:**")
    lines.append("")
    lines.append("1. **Lexical** — a trigger below matches → `Read` the skill's `SKILL.md`.")
    lines.append("2. **Semantic** — nothing matches but the intent is clear → "
                 "`osforge-db search-semantic \"<intent>\"`, then `buscar-skill.py <term>`.")
    lines.append("3. **Promote** — the skill will be needed again in this project → "
                 "`install-skill.sh <name>` makes it native from the next session on.")
    lines.append("")
    # The root is a placeholder, substituted with the real absolute path by
    # deploy.sh. A relative `skills/<name>/` would resolve only inside the
    # OSForge repo — and non-core skills are needed in SATELLITE projects, where
    # that directory does not exist. Baking an absolute path into the repo copy
    # instead would make the manifest machine-specific and break `--check`
    # across machines.
    lines.append(f"**Path rule:** `{SKILLS_ROOT_TOKEN}/<name>/SKILL.md`. "
                 "Only paths that differ are shown in parentheses.")
    lines.append("")
    lines.append("**Heavy skills** (`offensive-*`, `imagegen-*`, `agency/*`) declare `model:`/`context: fork` "
                 "in their frontmatter — dispatch a subagent to read them instead of reading inline.")
    lines.append("")

    by_cat: dict[str, list[dict]] = {}
    for s in non_core:
        by_cat.setdefault(s["category"], []).append(s)

    for cat in sorted(by_cat, key=lambda c: (-len(by_cat[c]), c)):
        lines.append(f"## {cat}")
        lines.append("")
        for s in sorted(by_cat[cat], key=lambda x: x["name"].lower()):
            # The path rule is `skills/<name>/SKILL.md`, so the path may only be
            # omitted when the directory really is the frontmatter name. Nested
            # skills AND renamed ones (skills/evolve -> name: osforge-evolve)
            # must show it, or the agent resolves a path that does not exist.
            suffix = "" if s["rel"] == s["name"] else f" (`{s['rel']}`)"
            lines.append(f"- **{s['name']}**{suffix} — {s['triggers']}")
        lines.append("")

    if live_knowledge:
        collisions = sum(1 for k in live_knowledge if k["duplicate_of"])
        lines.append("## 📄 Knowledge modules (legacy flat format)")
        lines.append("")
        lines.append("Condensed reference notes, not skills — no frontmatter. Path: `skills/<shown>`.")
        if collisions:
            lines.append("")
            lines.append(
                f"**Precedence:** {collisions} of these share a name with a skill (marked ⇄). "
                "The skill is the expanded version — read it first and treat the note as a "
                "condensed supplement. Never load both."
            )
        lines.append("")
        for k in live_knowledge:
            mark = f" ⇄ skill `{k['duplicate_of']}`" if k["duplicate_of"] else ""
            lines.append(f"- **{k['name']}** (`{k['rel']}`){mark} — {k['triggers']}")
        lines.append("")

    lines.append(END)
    return "\n".join(lines)


def splice(block: str) -> tuple[str, bool]:
    md = SKILLS_MD.read_text(encoding="utf-8")
    if START in md and END in md:
        pre = md[: md.index(START)]
        post = md[md.index(END) + len(END):]
        new = pre + block + post
    else:
        raise SystemExit(
            f"markers not found in {SKILLS_MD.relative_to(BASE)} — add:\n{START}\n{END}"
        )
    return new, new != md


# ── reporting ────────────────────────────────────────────────────────────────

def report(skills: list[dict], knowledge: list[dict], core: set[str]) -> None:
    known = {s["rel"] for s in skills}
    print(f"skills (SKILL.md):      {len(skills)}")
    print(f"  core (native):        {len([s for s in skills if s['rel'] in core])}")
    print(f"  manifest (on-demand): {len([s for s in skills if s['rel'] not in core])}")

    ghosts = sorted(core - known)
    if ghosts:
        print(f"\n!! {len(ghosts)} entries in skills-core.txt point at nothing:")
        for g in ghosts:
            print(f"   {g}")

    dups = [k for k in knowledge if k["duplicate_of"]]
    print(f"\nknowledge modules:      {len(knowledge)} (all indexed)")
    print(f"  name collisions:      {len(dups)}  <- merge debt, NOT duplicates")
    print("  content overlap with the same-named skill is 6-89%: the flat note is an")
    print("  older condensed generation, the skill the expanded one. Merging is a")
    print("  per-pair human call; deleting on filename alone destroys material.")
    for k in dups:
        print(f"   skills/{k['rel']}  <->  skill '{k['duplicate_of']}'")

    missing = [s for s in skills if not s["desc"]]
    if missing:
        print(f"\n{len(missing)} skills with no frontmatter description (trigger inferred from dir name):")
        for s in missing:
            print(f"   {s['rel']}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 if the block is stale")
    ap.add_argument("--stdout", action="store_true", help="print the block, write nothing")
    ap.add_argument("--report", action="store_true", help="coverage + duplication report")
    args = ap.parse_args()

    core = load_core()
    skills = collect_skills()
    knowledge = collect_knowledge()

    if args.report:
        report(skills, knowledge, core)
        return 0

    block = render(skills, knowledge, core)

    if args.stdout:
        print(block)
        return 0

    new, changed = splice(block)

    if args.check:
        if changed:
            print("SKILLS.md manifest is STALE — run: python3 scripts/_generate_manifest.py", file=sys.stderr)
            return 1
        print("SKILLS.md manifest is up to date.")
        return 0

    if changed:
        SKILLS_MD.write_text(new, encoding="utf-8")
        print(f"manifest written to {SKILLS_MD.relative_to(BASE)} "
              f"({len([s for s in skills if s['rel'] not in core])} skills, "
              f"{len([k for k in knowledge if not k['duplicate_of']])} knowledge modules)")
    else:
        print("manifest already up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
